name: Build and publish
on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  build_latest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag: [jammy]
        image: [carlosalgms/docker-apache-multi-php-versions]
        latest: [jammy]

    env:
      TAGGED_IMAGE: ${{ matrix.image }}:${{ matrix.tag }}
      TAGS: ${{ matrix.tag == matrix.latest && format('{0}:latest,', matrix.image) || '' }}${{ matrix.image }}:${{ matrix.tag }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        id: docker_login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: .
          pull: true
          push: true
          platforms: linux/amd64,linux/arm64
          # platforms: linux/amd64,linux/arm64,linux/arm/v7
          cache-from: ${{ env.TAGGED_IMAGE }}
          cache-to: type=inline
          build-args: ${{ matrix.buildArgs }}
          tags: ${{ env.TAGS }}
